Repository hyqe/brigand, pull requests merged in 2023-05, with the labels that each got.

#5 boilerplate
  Dockerfile
  README.md
  go.mod
  go.sum
  internal/handlers/create_file.go
  internal/handlers/create_file_test.go
  internal/handlers/get_file.go
  internal/handlers/health.go
  internal/handlers/health_test.go
  internal/server/config.go
  internal/server/routes.go
  internal/server/run.go
  internal/storage/metadata.go
  internal/storage/metadata_mock.go
  internal/storage/model.go
  internal/storage/mongo.go
  main.go
Labels: enhancement

#7 remove header validation
  .gitignore
  internal/server/routes.go
Labels: bug

#6 handcrafted MockMetadataClient
  internal/handlers/create_file_test.go
  internal/storage/metadata.go
  internal/storage/metadata_mock.go
Labels: enhancement

#14 Graceful shutdown
  internal/server/run.go
  internal/server/run_test.go
Labels: bug

#15 use timber v0.1.0
  go.mod
  go.sum
  internal/server/run.go
  internal/server/run_test.go
Labels: enhancement

#25 23 oas
  .gitignore
  Dockerfile
  internal/handlers/docs.go
  internal/server/routes.go
  openapi.yaml
  redocly.yaml
  scripts/compile_openapi.sh
Labels: enhancement

#30 add docker-compose for local testing
  README.md
  scripts/docker-compose-local.yaml
Labels: enhancement

#41 Define get file by name endpoint
  openapi.yaml
Labels: documentation

#42 Implement create file handler
  internal/handlers/create_file.go
  internal/handlers/create_file_test.go
  internal/server/routes.go
  internal/server/run.go
  internal/storage/digital_ocean_s3.go
  scripts/docker-compose-local.yaml
  scripts/localstack/s3.sh
Labels: enhancement

#44 Adds symlinks
  internal/handlers/make_symlink.go
  internal/handlers/symlink_make_test.go
  internal/handlers/symlink_take_test.go
  internal/handlers/take_symlink.go
  internal/server/config.go
  internal/server/routes.go
  internal/server/run.go
  internal/storage/symlink.go
Labels: enhancement
